HildaLibraryBundle_homepage:
    path:     /
    defaults: { _controller: HildaLibraryBundle:Page:index }
    requirements:
        _method: GET

HildaLibraryBundle_editorials:
    path:     /editorials
    defaults: { _controller: HildaLibraryBundle:Page:editorials}
    requirements:
        _method: GET

HildaLibraryBundle_authors:
    path:     /authors
    defaults: { _controller: HildaLibraryBundle:Page:authors}
    requirements:
        _method: GET

HildaLibraryBundle_books:
    path:     /books
    defaults: { _controller: HildaLibraryBundle:Page:books}
    requirements:
        _method: GET

HildaLibraryBundle_copies:
    path:     /copies
    defaults: { _controller: HildaLibraryBundle:Page:copies}
    requirements:
        _method: GET

HildaLibraryBundle_neweditorial:
    path:     /neweditorial
    defaults: { _controller: HildaLibraryBundle:Page:neweditorial}
    requirements:
        _method: GET

HildaLibraryBundle_newauthor:
    path:     /newauthor
    defaults: { _controller: HildaLibraryBundle:Page:newauthor}
    requirements:
        _method: GET

HildaLibraryBundle_newbook:
    path:     /newbook
    defaults: { _controller: HildaLibraryBundle:Page:newbook}
    requirements:
        _method: GET

HildaLibraryBundle_newcopy:
    path:     /newcopy
    defaults: { _controller: HildaLibraryBundle:Page:newcopy}
    requirements:
        _method: GET